"""
Django settings for inhouse_api project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-jv_^d7@e-do=221yklpew)xp52)nw-+7!b)7n+_f60_q97nl%6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # 3rd-party
    'rest_framework',

    # Core app
    'core',

    # Custom apps
    'players',
    'matches',
    'seasons',
    'season_players',
    'player_matches',
    'authentication',
    'season_player_lanes',
    'champions',
    'staff',
    'champion_tier_list',
    'inqueue',
]

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}


JAZZMIN_SETTINGS = {
    "site_title": "InHouse Admin",
    "site_header": "InHouse Admin Dashboard",
    "site_brand": "InHouse",
    "welcome_sign": "Bem-vindo(a) ao painel InHouse!",
    "copyright": "LeagueOfHu3BR © 2025",
    "search_model": "players.player",  # Exemplo: busca direta no modelo Player
    "show_ui_builder": False,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": ["players", "seasons", "matches", "staff"],
    "custom_css": None,
    "custom_js": None,
    "site_logo": "img/inhouse_icon.ico",
    "site_icon": "img/inhouse_icon.ico",
}

JAZZMIN_UI_TWEAKS = {
    "dark_mode": True,
    "theme": "darkly",  # tema dark do Bootstrap
    "accent": "success",  # verde (muda cor dos botões, links)
    "navbar_color": "navbar-dark bg-dark",  # barra superior bem escura
    "footer_small_text": True,
    "body_small_text": False,
    "brand_small_text": False,
    "navbar_small_text": True,
}



JAZZMIN_UI_TWEAKS["menu"] = [
    {"app": "players", "label": "Jogadores", "icon": "fas fa-users"},
    {"app": "seasons", "label": "Temporadas", "icon": "fas fa-calendar"},
    {"app": "matches", "label": "Partidas", "icon": "fas fa-gamepad"},
    {"app": "player_matches", "label": "Players nas Partidas", "icon": "fas fa-user-check"},
    {"app": "season_player_lanes", "label": "Estatísticas por Rota", "icon": "fas fa-map"},
    {"app": "staff", "label": "Staff", "icon": "fas fa-user-shield"},
]


REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'inhouse_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'inhouse_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
BASE_DIR = Path(__file__).resolve().parent.parent
STATICFILES_DIRS = [BASE_DIR / "static"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
